language: c
compiler:
  - gcc
  - clang
env:
  - CONFIGURE_ARGS=""
  - CONFIGURE_ARGS="--without-ldap"
  - CONFIGURE_ARGS="--without-cr"
  - CONFIGURE_ARGS="--without-ldap --without-cr"
before_install:
  - sudo add-apt-repository -y ppa:yubico/stable
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y --no-install-recommends libykclient-dev libpam0g-dev libldap2-dev libykpers-1-dev libyubikey-dev asciidoc docbook-xml xsltproc libxml2-utils
script: autoreconf -i && ./configure $CONFIGURE_ARGS && make check
