#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
PAM ArduKey configuration program

Copyright 2015 Philipp Meisberger <team@pm-codeworks.de>,
               Bastian Raschke <bastian.raschke@posteo.de>
All rights reserved.
"""

import os
import getpass
import argparse

import pamardukey.configuration as Config
from pamardukey import __version__ as VERSION


def showConfirmationDialog(question = ''):
    """
    Show confirmation dialog.

    @param string question
    @return bool
    """

    answer = raw_input(question + ' (Y/n)')

    if ( answer not in ['y', 'Y', ''] ):
        return False
    else:
        return True

def addUser(userName):
    """
    Add a new user to PAM ArduKey.

    @param string userName
    @return bool
    """

    ## Users can only change their own configuration
    if ( getpass.getuser() != userName ):
        print('You ('+ getpass.getuser() +') cannot add another user ('+ userName +')!')
        return False

    ## Confirmation dialog
    if ( showConfirmationDialog('Are you sure you want to add the user "' + userName + '"?') == False ):
        print('Adding user canceled.')
        return False

    ## Tries to init mapping file in users home directory
    try:
        mappingFile = Config.Configuration(os.getenv('HOME') + '/.pam-ardukey.mapping')

        ## Public ID exists in mapping file?
        if ( mappingFile.exists('Public_id', 'Mapping') and
            showConfirmationDialog('Public_id already exists! Do you want to override?') == False ):
            print('Adding user canceled.')
            return False

        publicId = raw_input('Please enter your "Public_id": ')

        if ( publicId == '' ):
            raise Exception('Public_id must not be empty!')

        mappingFile.set('Public_id', publicId, 'Mapping')

        if ( mappingFile.saveFile() == False ):
            raise Exception('Could not save configuration file in home directory!')

        print('Successfully added user "'+ userName +'"!')

    except Exception as e:
        print('Error occured while parsing mapping file: '+ str(e))
        return False

    return True

def removeUser(userName):
    """
    Remove user from configuration.

    @param string userName
    @return bool
    """

    ## Users can only change their own configuration
    if ( getpass.getuser() != userName ):
        print('You ('+ getpass.getuser() +') cannot add another user ('+ userName +')!')
        return False

    ## Confirmation dialog
    if ( showConfirmationDialog('Are you sure you want to remove the user "' + userName + '"?') == False ):
        print('Removing user canceled.')
        return False

   ## Tries to init mapping file in users home directory
    try:
        os.remove(os.getenv('HOME') + '/.pam-ardukey.mapping')
        print('Successfully removed user "'+ userName +'"!')

    except Exception as e:
        print('Error occured while parsing mapping file: '+ str(e))
        return False

    return True


if ( __name__ == '__main__' ):

    parser = argparse.ArgumentParser(add_help=True,
        description='PAM ArduKey configuration program ' + VERSION)

    parser.add_argument('-v', '--version',
        action='version',
        version='PAM ArduKey configuration program ' + VERSION,
        help='Prints version and exit.'
    )

    parser.add_argument('--add-user',
        action='store',
        default=False,
        required=False,
        nargs=1,
        metavar='NAME',
        type=str,
        help='Adds a new user.'
    )

    parser.add_argument('--remove-user',
        action='store',
        default=False,
        required=False,
        nargs=1,
        metavar='NAME',
        type=str,
        help='Removes a user.'
    )

    args = vars(parser.parse_args())

    if ( args['add_user'] ):
        addUser(args['add_user'][0])

    elif ( args['remove_user'] ):
        removeUser(args['remove_user'][0])

    else:
        parser.print_help()
